version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: employee
      POSTGRES_PASSWORD: maintencence
      POSTGRES_DB: EMN8
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
